import { Product, Category, BlogPost, BusinessProfile, WholesaleEnquiry, BusinessStarterLead } from './types';

export const businessProfile: BusinessProfile = {
  brandName: 'JYOTI ENTERPRISE',
  tagline: 'YOUR WHOLESALE GARMENT PARTNER FOR GROWING BUSINESSES',
  supportingMessage: 'Quality garments at wholesale prices for retailers, resellers and new clothing businesses.',
  whatsappNumber: '919876543210', // Configurable in Admin Settings
  displayWhatsapp: '[WHATSAPP NUMBER]',
  displayPhone: '[PHONE NUMBER]',
  displayEmail: '[EMAIL]',
  displayAddress: '[BUSINESS ADDRESS]',
  businessHours: 'Monday – Saturday: 10:00 AM – 7:30 PM (Sunday Closed)',
  primaryLocation: 'Garment Wholesale Market Hub',
};

export const categories: Category[] = [
  {
    id: 'cat-womens-wear',
    name: "Women's Wear",
    slug: 'womens-wear',
    image: '/images/cat-1-ref.jpg',
    description: 'Comprehensive wholesale collection of contemporary and traditional women’s garments for boutiques and retailers.',
    badge: 'Popular',
  },
  {
    id: 'cat-kurtis',
    name: 'Kurtis',
    slug: 'kurtis',
    image: '/images/cat-2-ref.jpg',
    description: 'Daily wear, festive, straight cut, and Anarkali kurtis crafted with tested color fastness and reliable stitching.',
    badge: 'Top Wholesale',
  },
  {
    id: 'cat-tops-dresses',
    name: 'Tops & Dresses',
    slug: 'tops-dresses',
    image: '/images/cat-3-ref.jpg',
    description: 'Fast-moving rayon tops, tunics, and dresses designed for urban boutiques and digital clothing resellers.',
    badge: 'High Margin',
  },
  {
    id: 'cat-kids-wear',
    name: 'Kids Wear',
    slug: 'kids-wear',
    image: '/images/cat-4-ref.jpg',
    description: 'Durable, skin-friendly festive kurtas and daily apparel engineered specifically for young demographics.',
    badge: 'High Repeat',
  },
];

export const initialProducts: Product[] = [
  {
    id: 'prod-womens-printed-kurti',
    slug: 'womens-printed-kurti',
    name: "Women's Printed Kurti",
    category: 'Kurtis',
    categorySlug: 'kurtis',
    description: 'Straight-cut printed ethnic kurti crafted from breathable rayon-cotton fabric. Features neat placket embroidery and pre-shrunk wash. Specially selected for high sell-through rates across retail counters.',
    fabric: 'Premium 140 GSM Rayon & Cotton Blend',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colours: ['Indigo Navy', 'Charcoal Grey', 'Maroon Wine', 'Deep Teal'],
    moq: 12,
    unit: 'pcs (Assorted Sizes & Colours)',
    price: null,
    showPrice: false,
    availability: 'In Stock',
    featured: true,
    image: '/images/cat-1-ref.jpg',
    gallery: ['/images/cat-1-ref.jpg', '/images/prod-kurti.jpg', '/images/kurti-editorial.jpg'],
    specifications: {
      'Sleeve Length': '3/4 Sleeves',
      'Stitching Standard': 'Interlocked 4-thread overlock',
      'Wash Care': 'Machine wash cold / Gentle cycle',
      'Packaging': 'Single piece polybag in wholesale bundle of 12',
    },
  },
  {
    id: 'prod-rayon-casual-tops',
    slug: 'rayon-casual-tops',
    name: 'Rayon Casual Tops',
    category: 'Tops & Dresses',
    categorySlug: 'tops-dresses',
    description: 'Versatile casual peasant top featuring subtle bohemian prints, comfortable neckline, and relaxed silhouette. Highly favored by college-wear and modern casual apparel retailers.',
    fabric: 'Ultra-soft Washed Slub Rayon',
    sizes: ['S', 'M', 'L', 'XL'],
    colours: ['Rust Crimson', 'Earthy Mustard', 'Olive Sage', 'Midnight Black'],
    moq: 18,
    unit: 'pcs (Assorted Sizes)',
    price: null,
    showPrice: false,
    availability: 'In Stock',
    featured: true,
    image: '/images/prod-2-ref.jpg',
    gallery: ['/images/prod-2-ref.jpg', '/images/cat-3-ref.jpg', '/images/ethnic-wear.jpg'],
    specifications: {
      'Sleeve Length': 'Elasticated Raglan / 3/4 Sleeves',
      'Fit Type': 'Comfort Casual Fit',
      'Length': 'Hip Length (26 inches)',
      'Wholesale Pack': 'Assorted sizes ratio 1:2:2:1',
    },
  },
  {
    id: 'prod-tops-and-dresses',
    slug: 'tops-and-dresses-flair',
    name: 'Tops & Dresses',
    category: 'Tops & Dresses',
    categorySlug: 'tops-dresses',
    description: 'Tiered flowy tunic dress with pleated chest yoke. Works as both a long tunic and knee-length dress. High margin opportunity for online and Instagram clothing resellers.',
    fabric: 'Textured Poly-Crepe with Cotton Voile Lining',
    sizes: ['S', 'M', 'L', 'XL'],
    colours: ['Forest Emerald', 'Dusty Rose', 'Ochre Gold', 'Powder Blue'],
    moq: 18,
    unit: 'pcs (Per Pack)',
    price: null,
    showPrice: false,
    availability: 'In Stock',
    featured: true,
    image: '/images/prod-3-ref.jpg',
    gallery: ['/images/prod-3-ref.jpg', '/images/cat-3-ref.jpg'],
    specifications: {
      'Pattern': 'Solid Texture with Smocked Details',
      'Transparency': 'Opaque (Lined)',
      'Occasion': 'Smart Casual / Day Outing',
      'Wholesale Minimum': '18 pcs mixed colours',
    },
  },
  {
    id: 'prod-kids-festive-wear',
    slug: 'kids-festive-wear',
    name: 'Kids Festive Wear',
    category: 'Kids Wear',
    categorySlug: 'kids-wear',
    description: 'Traditional boy’s festive kurta pajama set with gold foil motifs and comfortable mandarin collar. Soft cotton lining ensures zero itching for young children, driving repeat family purchases.',
    fabric: 'Chanderi Jacquard with 100% Cotton Inner Lining',
    sizes: ['2-3 Yrs', '4-5 Yrs', '6-7 Yrs', '8-10 Yrs'],
    colours: ['Marigold Yellow', 'Royal Maroon', 'Coral Peach', 'Emerald Green'],
    moq: 12,
    unit: 'sets (Kurta + Pajama)',
    price: null,
    showPrice: false,
    availability: 'In Stock',
    featured: true,
    image: '/images/cat-4-ref.jpg',
    gallery: ['/images/cat-4-ref.jpg', '/images/prod-4-ref.jpg'],
    specifications: {
      'Included Components': '1 Kurta, 1 Cotton Churidar Pajama',
      'Closure': 'Front Button Placket',
      'Lining': '100% Cotton Voile throughout',
      'Season': 'All-Season Festive & Wedding',
    },
  },
  {
    id: 'prod-anarkali-kurti-set',
    slug: 'embroidered-anarkali-kurti-set',
    name: 'Embroidered Anarkali Kurti Set',
    category: 'Kurtis',
    categorySlug: 'kurtis',
    description: 'Floor-sweep flair Anarkali with intricate yoke embroidery and coordinated dupatta. Engineered for bridal party guests and festive retail displays.',
    fabric: 'Heavy Rayon 160 GSM with Nazneen Dupatta',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colours: ['Deep Wine', 'Peacock Blue', 'Bottle Green', 'Mustard'],
    moq: 10,
    unit: 'sets (Kurti + Pants + Dupatta)',
    price: null,
    showPrice: false,
    availability: 'In Stock',
    featured: false,
    image: '/images/cat-2-ref.jpg',
    gallery: ['/images/cat-2-ref.jpg', '/images/kurti-editorial.jpg'],
    specifications: {
      'Flare': '3.2 Meters Kali Cut',
      'Embroidery': 'Zari & Thread Work',
      'Dupatta Length': '2.25 Meters with Lace Border',
    },
  },
  {
    id: 'prod-cotton-daily-kurtis',
    slug: 'straight-cut-daily-wear-kurtis',
    name: 'Straight Cut Daily Wear Kurtis',
    category: 'Kurtis',
    categorySlug: 'kurtis',
    description: 'High-turnover daily workwear cotton kurtis. Color guaranteed, breathable, and designed for price-conscious retail customers.',
    fabric: '100% Pure 60x60 Cotton',
    sizes: ['M', 'L', 'XL', 'XXL', '3XL'],
    colours: ['Pastel Mint', 'Peach Blossom', 'Sky Azure', 'Lilac'],
    moq: 24,
    unit: 'pcs',
    price: null,
    showPrice: false,
    availability: 'In Stock',
    featured: false,
    image: '/images/kurti-editorial.jpg',
    gallery: ['/images/kurti-editorial.jpg', '/images/cat-1-ref.jpg'],
    specifications: {
      'Shrinkage': 'Pre-washed (under 1.5%)',
      'Length': 'Calf Length (44 inches)',
      'Wholesale Pack': '6 sizes, 4 colours bundle',
    },
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: 'how-to-start-a-garment-business',
    title: 'How to Start a Garment Business',
    subtitle: 'A practical, step-by-step roadmap for launching your retail or online clothing store.',
    category: 'Business Startup',
    readTime: '6 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'From identifying your target customer to finding wholesale suppliers and calculating your initial stock requirements, here is the realistic guide to starting a clothing venture.',
    summary: 'Starting a clothing business is one of India’s most proven retail paths when approached with disciplined inventory management and reliable wholesale relationships.',
    keyTakeaways: [
      'Focus on a narrow category first (e.g. Kurtis or Casual Tops) rather than trying to stock everything.',
      'Maintain at least 30-40% of your starting capital in reserve for reorders of fast-moving items.',
      'Partner with wholesale suppliers who offer low MOQs so you can test market response without dead inventory.',
    ],
    sections: [
      {
        heading: '1. Define Your Specific Retail Niche',
        body: [
          'The most common pitfall for new garment entrepreneurs is attempting to cater to men, women, and children all at once. Specializing in women’s ethnic wear, daily wear kurtis, or western casual tops allows you to curate an appealing collection with a modest starting budget.',
          'Identify who your immediate buyers are: college students, working professionals, homemakers, or boutique clientele looking for festive wear.',
        ],
      },
      {
        heading: '2. Wholesale Sourcing Strategy',
        body: [
          'Wholesale pricing directly determines your gross margin. Look for wholesale partners that provide consistent sizing, pre-shrunk fabrics, and transparent bundle specifications.',
          'Establish open communication with your supplier to understand which designs have the highest repeat orders in current market cycles.',
        ],
      },
    ],
  },
  {
    slug: 'how-much-money-do-you-need-to-start-a-clothing-business',
    title: 'How Much Money Do You Need to Start a Clothing Business?',
    subtitle: 'Realistic budget breakdowns for home sellers, Instagram boutiques, and retail counters.',
    category: 'Budgeting & Finance',
    readTime: '5 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'Understand working capital needs: inventory costs, packaging, shipping, and emergency reserves across ₹25,000 to ₹2 Lakh tiers.',
    summary: 'A clear financial breakdown demonstrating that an online clothing business can start with ₹25,000–₹50,000, while physical retail spaces require ₹1 Lakh and above.',
    keyTakeaways: [
      'Inventory should represent 60% of your initial investment.',
      'Keep 25% for packaging, shipping logistics, and photography.',
      'Retain 15% liquid buffer for reordering best-selling sizes.',
    ],
    sections: [
      {
        heading: 'Tier 1: Reselling & Social Commerce (₹15,000 – ₹35,000)',
        body: [
          'If you are starting on WhatsApp, Instagram, or Facebook Marketplace, you do not need retail rental expenses. Your entire capital goes toward initial curated sample batches (2-3 master wholesale bundles).',
          'This allows you to take customer photos, record video reels of fabric drape, and test demand with zero overhead.',
        ],
      },
      {
        heading: 'Tier 2: Dedicated Online Boutique (₹50,000 – ₹1,00,000)',
        body: [
          'With ₹50,000 to ₹1 Lakh, you can source 80 to 180 assorted pieces across 3 popular categories, offer fast dispatch, and establish branded packaging.',
        ],
      },
    ],
  },
  {
    slug: 'how-to-choose-wholesale-garments',
    title: 'How to Choose Wholesale Garments for Fast Sell-Through',
    subtitle: 'Criteria for evaluating fabric quality, stitching durability, and customer appeal.',
    category: 'Inventory Sourcing',
    readTime: '5 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'Learn how to inspect fabric GSM, seam allowances, colorfastness, and size charts before placing bulk wholesale orders.',
    summary: 'How smart retailers curate their inventory to avoid dead stock and maximize inventory turnover speed.',
    keyTakeaways: [
      'Always verify fabric GSM and shrinkage tolerance.',
      'Check size gradation: standard Indian sizing must allow comfort at hips and bust.',
      'Select designs that photograph well for online and catalog viewing.',
    ],
    sections: [
      {
        heading: 'Fabric Quality Over Flashy Prints',
        body: [
          'A customer will buy a garment once for its print, but will only return to your shop if the fabric holds up after washing. Prioritize rayon slub, combed cotton, and durable georgette blends that drape elegantly without losing color.',
        ],
      },
    ],
  },
  {
    slug: 'how-to-calculate-garment-profit',
    title: 'How to Calculate Garment Profit & Pricing Margins',
    subtitle: 'Understanding wholesale landed cost, overheads, and retail pricing formulas.',
    category: 'Profitability',
    readTime: '4 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'Formulas for calculating Gross Margin, Net Margin, and Mark-ups to ensure your garment business remains profitable.',
    summary: 'Master the numbers behind wholesale sourcing and retail markups to ensure healthy cash flow.',
    keyTakeaways: [
      'Wholesale landed cost = Garment Wholesale Price + Freight/Logistics per piece + Packaging.',
      'Aim for 50% to 100% markup on casual retail garments.',
      'Track dead stock markdown allowances in your monthly P&L.',
    ],
    sections: [
      {
        heading: 'The True Landed Cost Formula',
        body: [
          'Never calculate your profit margin purely from the wholesale invoice price. Always add parcel freight per piece, individual polybag/box packaging, and GST if applicable.',
        ],
      },
    ],
  },
  {
    slug: 'wholesale-vs-retail-garments',
    title: 'Wholesale vs Retail Garments: What New Sellers Must Know',
    subtitle: 'Key differences in packaging, bundle assortments, MOQs, and pricing tiers.',
    category: 'Industry Basics',
    readTime: '4 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'Demystifying master packs, catalog sets, color ratios, and how wholesale supply chains function.',
    summary: 'A foundational overview explaining why wholesale purchases happen in sets/ratios and how to leverage this for retail profitability.',
    keyTakeaways: [
      'Wholesale garments are sold in sets of assorted sizes or color sets.',
      'Buying in bulk unlocks pricing tiers that allow 40-70% retail profit margins.',
    ],
    sections: [
      {
        heading: 'Why Wholesale Bundles Use Size Ratios',
        body: [
          'Wholesale manufacturers produce clothing in size curves (e.g. 1 M, 2 L, 2 XL, 1 XXL). Understanding this allows you to price fast-moving sizes strategically and bundle slower-moving sizes into promotional offers.',
        ],
      },
    ],
  },
  {
    slug: 'how-much-stock-should-a-new-retailer-buy',
    title: 'How Much Stock Should a New Retailer Buy?',
    subtitle: 'Inventory planning principles to prevent dead stock while maintaining variety.',
    category: 'Inventory Management',
    readTime: '5 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'Rule of thumb formulas for initial inventory depth, SKU variety, and replenishment timing.',
    summary: 'Prevent the two biggest inventory dangers: buying too much slow-moving stock or running out of bestsellers.',
    keyTakeaways: [
      'Aim for variety in design, not extreme depth in single styles on your first order.',
      'Start with 3-5 categories and 4-6 designs per category.',
      'Set an inventory turnaround target of 30 to 45 days.',
    ],
    sections: [
      {
        heading: 'The 70-30 Inventory Rule',
        body: [
          'Invest 70% of your starting budget in proven, daily-wear commercial styles that have predictable demand. Allocate only 30% to trendy or high-risk statement pieces.',
        ],
      },
    ],
  },
  {
    slug: 'how-to-start-an-instagram-clothing-business',
    title: 'How to Start an Instagram Clothing Business',
    subtitle: 'Actionable steps to launch, photograph, and sell wholesale garments on social media.',
    category: 'Social Commerce',
    readTime: '6 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'How to stage product photos, write conversion captions, handle WhatsApp inquiries, and manage fast dispatches.',
    summary: 'A complete playbook for turning wholesale garments into high-margin Instagram orders.',
    keyTakeaways: [
      'Natural lighting and honest video reels convert significantly better than overly edited photos.',
      'Direct WhatsApp chat links in your bio reduce customer friction by 70%.',
      'Maintain clear size guides with bust and hip measurements in inches.',
    ],
    sections: [
      {
        heading: 'Creating High-Converting Product Reels',
        body: [
          'Show the fabric texture up close, demonstrate the neckline stitch, and capture the natural drape when walking. Customers buying clothes online want certainty regarding fabric quality and color accuracy.',
        ],
      },
    ],
  },
  {
    slug: 'how-to-find-the-right-garment-supplier',
    title: 'How to Find the Right Garment Supplier for Long-Term Growth',
    subtitle: 'Questions to ask, warning signs, and establishing reliable wholesale partnerships.',
    category: 'Supplier Sourcing',
    readTime: '5 min read',
    publishedDate: 'Oct 2026',
    excerpt: 'Checklist for evaluating wholesale garment suppliers: communication speed, sample policies, defect returns, and reorder predictability.',
    summary: 'Finding the right wholesale supplier is the single most critical partnership in your garment business.',
    keyTakeaways: [
      'Reliability of repeat stock matters more than a 2-rupee price discount on a one-off lot.',
      'Confirm whether the supplier supports small retailers with manageable MOQs.',
      'Verify how quickly orders are packed and dispatched after confirmation.',
    ],
    sections: [
      {
        heading: 'Prioritize Supply Continuity',
        body: [
          'When an item becomes a viral bestseller in your shop, you need a supplier who can restock the same fabric quality and colorway quickly. Look for partners who maintain disciplined wholesale production pipelines.',
        ],
      },
    ],
  },
];

export const sampleEnquiries: WholesaleEnquiry[] = [
  {
    id: 'enq-101',
    createdAt: '2026-10-08T11:20:00Z',
    name: 'Priya Sharma',
    businessName: 'Priya Boutique & Studio',
    phone: '+91 98200 XXXXX',
    whatsapp: '+91 98200 XXXXX',
    city: 'Pune, Maharashtra',
    businessType: 'Boutique',
    interestedProducts: ["Women's Printed Kurti", 'Embroidered Anarkali Kurti Set'],
    approxQuantity: '50 - 100 pcs',
    budget: '₹25,000–₹50,000',
    message: 'Starting festive season collection. Interested in your rayon kurtis and Anarkali catalog with wholesale rate card.',
    status: 'New',
    leadSource: 'quote_modal',
    notes: ['Inquired about express parcel dispatch to Pune.', 'Follow up scheduled for tomorrow.'],
  },
  {
    id: 'enq-102',
    createdAt: '2026-10-07T15:45:00Z',
    name: 'Rahul Verma',
    businessName: 'RV Fashions Online',
    phone: '+91 97110 XXXXX',
    whatsapp: '+91 97110 XXXXX',
    city: 'Jaipur, Rajasthan',
    businessType: 'Online Store / Instagram Seller',
    interestedProducts: ['Rayon Casual Tops', 'Tops & Dresses'],
    approxQuantity: '100 - 200 pcs',
    budget: '₹50,000–₹1 Lakh',
    message: 'We sell on Instagram and need reliable weekly replenishment for women tops and tunics.',
    status: 'Quotation Sent',
    leadSource: 'hero_cta',
    notes: ['Catalog and wholesale price list PDF sent via WhatsApp.', 'Customer reviewing MOQ per color.'],
  },
  {
    id: 'enq-103',
    createdAt: '2026-10-06T09:30:00Z',
    name: 'Anita Desai',
    businessName: 'Desai Garment Emporium',
    phone: '+91 94220 XXXXX',
    whatsapp: '+91 94220 XXXXX',
    city: 'Surat, Gujarat',
    businessType: 'Physical Clothing Shop',
    interestedProducts: ['Kids Festive Wear', "Women's Printed Kurti"],
    approxQuantity: '200+ pcs',
    budget: '₹1 Lakh+',
    message: 'Running a 15-year old family clothing shop. Need consistent vendor for kids festive and daily wear kurtis.',
    status: 'Contacted',
    leadSource: 'product_enquiry',
    notes: ['Spoke on phone. Sending fabric swatches and trial bundle.'],
  },
];

export const sampleBusinessStarterLeads: BusinessStarterLead[] = [
  {
    id: 'start-201',
    createdAt: '2026-10-08T10:15:00Z',
    businessType: 'Instagram/Facebook Business',
    budgetRange: '₹25,000–₹50,000',
    garments: ["Women's Wear", 'Tops & Dresses', 'Kurtis'],
    name: 'Meenakshi Iyer',
    phone: '+91 98450 XXXXX',
    city: 'Bengaluru',
    status: 'New',
    notes: ['Wants advice on top 3 styles for starting on social media.'],
  },
  {
    id: 'start-202',
    createdAt: '2026-10-07T18:00:00Z',
    businessType: 'Physical Clothing Shop',
    budgetRange: '₹50,000–₹1 Lakh',
    garments: ['Kurtis', 'Kids Wear'],
    name: 'Suresh Patel',
    phone: '+91 98980 XXXXX',
    city: 'Ahmedabad',
    status: 'Contacted',
    notes: ['Opening shop next month in retail market.'],
  },
];
